
############################################################
# You can ignore this file unless you are hosting the demo #
############################################################


server {
    domains: "glitter-demo.{localhost,lstv.space}";
    root: "/demo";
}

# ls version: "5.2.8";
ls version: "beta";

addon("~/demo/.backend_task");
browserSupport { chrome: 134; firefox: 130 }
