
############################################################
# You can ignore this file unless you are hosting the demo #
############################################################


server {
    domains: glitter-demo.localhost;
    root: "/demo";
}

case_override(akeno_version[">=1.7.0"]) {
    server (default) {
        route("glitter-demo.localhost", "lstv.space/tech/glitter/playground/**");

        hsts;
        root: "/demo";
    }
}

# ls version: "5.2.8";
ls version: "beta";

addon("~/demo/.backend_task");
browserSupport { chrome: 134; firefox: 130 }